In [1]:
import pandas as pd

raw_df = pd.read_csv('../data/call-quality.csv')

In [2]:
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104334 entries, 0 to 104333
Data columns (total 10 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   inout_travelling   104334 non-null  object
 1   operator           104334 non-null  object
 2   network_type       104316 non-null  object
 3   rating             104334 non-null  int64
 4   calldrop_category  104334 non-null  object
 5   latitude           104334 non-null  float64
 6   longitude          104334 non-null  float64
 7   state_name         58609 non-null   object
 8   month              104334 non-null  int64
 9   year               104334 non-null  int64
dtypes: float64(2), int64(3), object(5)
memory usage: 8.0+ MB

In [3]:
(raw_df.isnull().sum()/raw_df.count())*100

inout_travelling      0.000000
operator              0.000000
network_type          0.017255
rating                0.000000
calldrop_category     0.000000
latitude              0.000000
longitude             0.000000
state_name           78.017028
month                 0.000000
year                  0.000000
dtype: float64

state name has the highest null value percentange

 """adding state names based on longitude and latitude"""
from src.utils import get_state_name
 """Apply the function to each row of the dataframe using apply"""
raw_df['state'] = raw_df.apply(get_state_name, axis=1)

In [4]:
raw_df.dropna(axis=0, inplace=True)

In [5]:
raw_df

,inout_travelling,operator,network_type,rating,calldrop_category,latitude,longitude,state_name,month,year
0,Indoor,RJio,4G,1,Poor Voice Quality,26.687119,82.171533,Uttar Pradesh,7,2022
1,Indoor,RJio,4G,1,Poor Voice Quality,26.687119,82.171533,Uttar Pradesh,7,2022
4,Travelling,VI,4G,4,Satisfactory,21.123036,79.067904,Maharashtra,7,2022
8,Indoor,RJio,4G,3,Satisfactory,19.225397,72.859307,Maharashtra,7,2022
10,Outdoor,VI,4G,4,Satisfactory,25.525933,87.032880,Bihar,7,2022
...,...,...,...,...,...,...,...,...,...,...
104327,Indoor,RJio,4G,5,Satisfactory,12.956510,77.489557,Karnataka,11,2023
104328,Outdoor,VI,4G,1,Poor Voice Quality,21.132335,79.068327,Maharashtra,11,2023
104329,Indoor,RJio,4G,5,Satisfactory,12.958151,77.484752,Karnataka,11,2023
104331,Indoor,Airtel,4G,3,Satisfactory,30.112252,78.295731,Uttarakhand,11,2023
104332,Indoor,Airtel,Unknown,3,Satisfactory,30.112252,78.295731,Uttarakhand,11,2023

In [6]:
print(raw_df['state_name'].unique())

['Uttar Pradesh' 'Maharashtra' 'Bihar' 'Karnataka' 'Tamil Nadu'
 'Telangana' 'Uttarakhand' 'Delhi' 'Odisha' 'Gujarat' 'Madhya Pradesh'
 'Assam' 'Meghalaya' 'Haryana' 'Chhattisgarh' 'Rajasthan' 'Jharkhand'
 'West Bengal' 'Andhra Pradesh' 'Kerala' 'Kashmir' 'Punjab' 'NA '
 'Himachal Pradesh' 'Goa' 'Nagaland' 'Jammu and Kashmir' 'Manipur'
 'Unnamed: 7' 'Puducherry' 'Laccadives' 'Tripura' 'Arunachal Pradesh'
 'Chandigarh' 'NCT' 'Mizoram']

In [7]:
print(raw_df['operator'].unique())

['RJio' 'VI' 'Airtel' 'BSNL' 'MTNL' 'Vodafone' 'Idea' '\ufeffIdea']

In [8]:
raw_df.replace({'\ufeffIdea':'Idea'},inplace=True)

In [9]:
no_loc_df = raw_df[(raw_df['state_name']==("NA " or 'Unnamed: 7')) ]
no_loc_df.reset_index(drop=True, inplace= True)

In [10]:
no_loc_df.to_csv(r"C:\Users\karthikeya\telecom_call_quality_anlaysis_and_prediction\data\no_location_data.csv")

In [11]:
raw_df[raw_df['state_name']=='Unnamed: 7']

,inout_travelling,operator,network_type,rating,calldrop_category,latitude,longitude,state_name,month,year
21168,Outdoor,VI,4G,3,Call Dropped,-1.0,-1.1,Unnamed: 7,2,2023
40575,Outdoor,RJio,4G,4,Satisfactory,-1.0,-1.1,Unnamed: 7,7,2022

In [12]:
raw_df

,inout_travelling,operator,network_type,rating,calldrop_category,latitude,longitude,state_name,month,year
0,Indoor,RJio,4G,1,Poor Voice Quality,26.687119,82.171533,Uttar Pradesh,7,2022
1,Indoor,RJio,4G,1,Poor Voice Quality,26.687119,82.171533,Uttar Pradesh,7,2022
4,Travelling,VI,4G,4,Satisfactory,21.123036,79.067904,Maharashtra,7,2022
8,Indoor,RJio,4G,3,Satisfactory,19.225397,72.859307,Maharashtra,7,2022
10,Outdoor,VI,4G,4,Satisfactory,25.525933,87.032880,Bihar,7,2022
...,...,...,...,...,...,...,...,...,...,...
104327,Indoor,RJio,4G,5,Satisfactory,12.956510,77.489557,Karnataka,11,2023
104328,Outdoor,VI,4G,1,Poor Voice Quality,21.132335,79.068327,Maharashtra,11,2023
104329,Indoor,RJio,4G,5,Satisfactory,12.958151,77.484752,Karnataka,11,2023
104331,Indoor,Airtel,4G,3,Satisfactory,30.112252,78.295731,Uttarakhand,11,2023
104332,Indoor,Airtel,Unknown,3,Satisfactory,30.112252,78.295731,Uttarakhand,11,2023

In [18]:
raw_df.to_csv(r"C:\Users\karthikeya\telecom_call_quality_anlaysis_and_prediction\data\call-quality-clean.csv", index=False)